// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // the following informations, values must not be shared 
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF-PIztodZLzj8u_fgMXlGRvgcWeIZmmM',
    appId: '1:419185066719:android:e55c9e866d903b2a549f6a',
    messagingSenderId: '419185066719',
    projectId: 'cleanifi-project',
    storageBucket: 'cleanifi-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1kWMsc6Dx73gohjwEWCnH9B40RvcVilQ',
    appId: '1:419185066719:ios:bb0d50388347a5d2549f6a',
    messagingSenderId: '419185066719',
    projectId: 'cleanifi-project',
    storageBucket: 'cleanifi-project.appspot.com',
    iosClientId: '419185066719-973ruk4v6b8fvdime85jt8gddahhl8tg.apps.googleusercontent.com',
    iosBundleId: 'nsu.summer2023.project.cleanifi',
  );
}
